# Write "glob" template to your Inecobank "Statement" files.
# Glob supports wildcard "star" (*) which replaces any substring in the path.
InecobankStatementFilesGlob: "Statement*.xml"
# Write "glob" template to your MyAmeria "History" files.
# Glob supports wildcard "star" (*) which replaces any substring in the path.
MyAmeriaHistoryFilesGlob: "History *.xls"
# Due to MyAmeria "History" files doesn't provide "is expense or income" information
# need to specify how to separate transactions. Supported 2 ways:
# 1. (reliable) specify your account(s) number (16 digits number) and all transactions
#    with "Beneficiary account" from this list would be treated as an income.
MyAmeriaMyAccounts:
# 2. (unreliable) specify substrings to search in "Details" of transactions
#     and if they found then such transaction would be treated as an income.
MyAmeriaIncomeSubstrings:
  - "Transfer to myself"
  - "Account replenishment"
  - "Cash deposit"
# Flag to output all information about the result.
detailedOutput: true
# Flag to aggregate all transactions with "Details" not matched with "substrings"
# from 'groupNamesToSubstrings' below into single group with name "unknown".
groupAllUnknownTransactions: true
# Which day of month use as start of the month.
# Sometimes it makes sense to analyze month from the "salary day. 
monthStartDayNumber: 1
# List of strings to ignore from list of transactions.
# May be useful if your are transferring between your accounts and statement from this account is provided.
# In this case extra incomes and expences won't appear.
ignoreSubstrings:
  - Փոխանցում իմ հաշիվների միջև, Account replenishment, InecoOnline
# Dictionary of group names to list of substrings to search in transaction's "Details" field.
# Note that order is not guaranteed.
groupNamesToSubstrings:
  Yandex Taxi:
    - YANDEX
  Health:
    - ARABKIR JMC
    - CRYSTAL DENTAL CLINIC
    - GEGHAMA\ABOVYAN 34 A
    - VARDANANTS
  Pharmacies:
    - PHARM
    - DIALAB
    - 36.6
    - NATALI FARM
    - THEOPHARMA
    - GEDEON RICHTER
  Groceries:
    - CHEESE MARKET
    - YEREVAN  CITY
    - YEREVAN CITY
    - EVRIKA
    - MARKET
    - FIESTA\19
    - FIX PRICE
    - MAQUR TUN
    - GRAND CANDY
  To other account:
    - Account replenishment
  Wildberries:
    - WILDBERRIES
  Cash:
    - INECO ATM
  Entertainment:
    - AQUATEK
    - EATERY
    - TASHIR PIZZA
    - KARAS
    - PLAY CITY
    - INSTITUTE OF BOTANY
  Subscriptions:
    - GOOGLE
    - SUBSCRIPTION
    - AWS EMEA
    - CLOUD
  Salary:
    - ամսվա աշխատավարձ
    - ԱՄՍՎԱ ԱՇԽԱՏԱՎԱՐՁ
